"""Initial migration after reset

Revision ID: 572bf6a6f0cb
Revises: 
Create Date: 2024-09-11 07:42:56.138724

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '572bf6a6f0cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('routine_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('feedbacks_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'routines', ['routine_id'], ['id'])
        batch_op.drop_column('routinue_id')

    with op.batch_alter_table('routines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_task_date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('adjustment', sa.String(length=512), nullable=True))
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', mysql.VARCHAR(length=20), nullable=False))
        batch_op.drop_column('adjustment')
        batch_op.drop_column('last_task_date')

    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('routinue_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('feedbacks_ibfk_1', 'routines', ['routinue_id'], ['id'])
        batch_op.drop_column('routine_id')

    # ### end Alembic commands ###
